# Generated by Django 3.2.16 on 2023-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='grade',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
