# Generated by Django 3.2.16 on 2023-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('added', 'added')], max_length=50)),
                ('obj_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text='Use the app password not your actual password for the security reason.', max_length=200, null=True)),
            ],
        ),
    ]
