# Generated by Django 3.2.16 on 2023-01-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('business_model', models.FileField(max_length=150, upload_to='participation/files/')),
                ('estimated_cost', models.FileField(max_length=150, upload_to='participation/files/')),
                ('estimated_timeframe', models.FileField(max_length=150, upload_to='participation/files/')),
                ('estimated_roi', models.FileField(max_length=150, upload_to='participation/files/')),
                ('project_detail', models.FileField(blank=True, max_length=150, null=True, upload_to='participation/files/')),
                ('noteworthy_impact', models.FileField(blank=True, max_length=150, null=True, upload_to='participation/files/')),
                ('noteworthy_mentions', models.FileField(blank=True, max_length=150, null=True, upload_to='participation/files/')),
                ('member', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
